### PR TITLE
Add support for rune pouch

### PR DESCRIPTION
**Pull request by kimbernator**
Tracks values of runes in the rune pouch

### CODE REVIEW

**Comment by mrhappyasthma** [comment]
I actually don't own a rune pouch yet to test this out. lol.

I'll work to grab one so that I can test this out.

**Comment by kimbernator** [comment]
Hah, no worries - I did some testing myself but it definitely wouldn't hurt to have someone else verify it.

**Comment by mrhappyasthma** [comment]
I bought a rune pouch. I'll pull this code locally and test it out later :)

**Comment by mrhappyasthma** [comment]
Did a pass of code review, and the code generally looks sound. I'll patch it in a bit and play around with it just to double check functionality and edge cases.

**Comment by mrhappyasthma** [comment]
Tested it out and it seems to work well. Thanks for this!

**Pull request merged**
